/*
 * Copyright [ 2024 - 2026 ] MapsMessaging B.V.
 */
package io.mapsmessaging.configuration.yaml;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.mapsmessaging.configuration.ConfigurationProperties;
import io.mapsmessaging.configuration.PropertyManager;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class YamlPropertyManagerCoverageTest {

  @TempDir
  Path tempDirectory;

  @Test
  void storeUsesInjectedClockForHeaderYear() throws Exception {
    Clock clock = Clock.fixed(
        Instant.parse("2031-06-15T12:00:00Z"),
        ZoneOffset.UTC
    );
    TestYamlPropertyManager manager = new TestYamlPropertyManager(clock);
    manager.add("sample", "value");

    manager.store(tempDirectory.toString(), "sample");

    String text = Files.readString(
        tempDirectory.resolve("sample.yaml"),
        StandardCharsets.UTF_8
    );
    assertTrue(text.contains("Copyright [ 2024 - 2031 ] [Maps Messaging B.V.]"));
    assertTrue(text.contains("# Autogenerated"));
    assertTrue(text.contains("value: expected"));
  }

  @Test
  void yamlRoundTripHelpersIncludeGlobalConfiguration() {
    TestYamlPropertyManager manager = new TestYamlPropertyManager(
        Clock.systemUTC()
    );
    manager.add("sample", "value");

    ConfigurationProperties global = new ConfigurationProperties();
    global.put("region", "test");
    manager.getProperties().setGlobal(global);

    String yaml = manager.yaml();

    assertTrue(yaml.contains("sample"));
    assertTrue(yaml.contains("global"));
    assertTrue(manager.toString().contains("region"));
  }

  @Test
  void copyCopiesPropertyValues() throws Exception {
    TestYamlPropertyManager source = new TestYamlPropertyManager(Clock.systemUTC());
    source.add("sample", "source");

    TestYamlPropertyManager target = new TestYamlPropertyManager(Clock.systemUTC());
    target.copy(source);

    assertEquals(
        "expected",
        target.getProperties("sample").getProperty("value")
    );
  }

  private static final class TestYamlPropertyManager extends YamlPropertyManager {

    private TestYamlPropertyManager(Clock clock) {
      super(clock);
    }

    private void add(String name, String ignored) {
      ConfigurationProperties value = new ConfigurationProperties();
      value.put("value", "expected");
      getProperties().put(name, value);
    }

    private String yaml() {
      return toYaml();
    }

    @Override
    public void load() {
    }

    @Override
    protected List<String> getKeys(String lookup) {
      return new ArrayList<>();
    }
  }
}
